# Generated by Django 3.1.1 on 2020-09-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=30)),
                ('exam_marks', models.IntegerField()),
                ('exam_time', models.IntegerField()),
                ('exam_questions', models.IntegerField()),
            ],
        ),
    ]
