# Generated by Django 3.1.1 on 2020-09-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exams',
            old_name='exam_questions',
            new_name='no_question',
        ),
        migrations.AddField(
            model_name='exams',
            name='exam_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='exam_name',
            field=models.TextField(max_length=30),
        ),
    ]
