# Generated by Django 3.1.1 on 2020-09-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_qna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='answer',
        ),
    ]
