# Generated by Django 3.1.1 on 2020-09-22 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_qna_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna', to='api.exams'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
