# Generated by Django 3.1.1 on 2020-09-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200922_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
